CREATE TABLE "CO"."ORDER_ITEMS" 
   (	"ORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LINE_ITEM_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER(10,2) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(*,0) NOT NULL ENABLE, 
	"SHIPMENT_ID" NUMBER(*,0), 
	 CONSTRAINT "ORDER_ITEMS_PK" PRIMARY KEY ("ORDER_ID", "LINE_ITEM_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ORDER_ITEMS_PRODUCT_U" UNIQUE ("PRODUCT_ID", "ORDER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ORDER_ITEMS_ORDER_ID_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "CO"."ORDERS" ("ORDER_ID") ENABLE, 
	 CONSTRAINT "ORDER_ITEMS_SHIPMENT_ID_FK" FOREIGN KEY ("SHIPMENT_ID")
	  REFERENCES "CO"."SHIPMENTS" ("SHIPMENT_ID") ENABLE, 
	 CONSTRAINT "ORDER_ITEMS_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "CO"."PRODUCTS" ("PRODUCT_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

COMMENT ON TABLE "CO"."ORDER_ITEMS" IS 'Details of which products the customer has purchased in an order';
COMMENT ON COLUMN "CO"."ORDER_ITEMS"."LINE_ITEM_ID" IS 'An incrementing number, starting at one for each order';
COMMENT ON COLUMN "CO"."ORDER_ITEMS"."ORDER_ID" IS 'The order these products belong to';
COMMENT ON COLUMN "CO"."ORDER_ITEMS"."PRODUCT_ID" IS 'Which item was purchased';
COMMENT ON COLUMN "CO"."ORDER_ITEMS"."QUANTITY" IS 'How many items of this product the customer purchased';
COMMENT ON COLUMN "CO"."ORDER_ITEMS"."SHIPMENT_ID" IS 'Where this product will be delivered';
COMMENT ON COLUMN "CO"."ORDER_ITEMS"."UNIT_PRICE" IS 'How much the customer paid for one item of the product';

