CREATE TABLE "CO"."ORDERS" 
   (	"ORDER_ID" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1951 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ORDER_TMS" TIMESTAMP (6) NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ORDER_STATUS" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"STORE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ORDERS_STATUS_C" CHECK ( order_status in
                    ( 'CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED')) ENABLE, 
	 CONSTRAINT "ORDERS_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CO"."CUSTOMERS" ("CUSTOMER_ID") ENABLE, 
	 CONSTRAINT "ORDERS_STORE_ID_FK" FOREIGN KEY ("STORE_ID")
	  REFERENCES "CO"."STORES" ("STORE_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

COMMENT ON TABLE "CO"."ORDERS" IS 'Details of who made purchases where';
COMMENT ON COLUMN "CO"."ORDERS"."CUSTOMER_ID" IS 'Who placed this order';
COMMENT ON COLUMN "CO"."ORDERS"."ORDER_ID" IS 'Auto-incrementing primary key';
COMMENT ON COLUMN "CO"."ORDERS"."ORDER_STATUS" IS 'What state the order is in. Valid values are:
OPEN - the order is in progress
PAID - money has been received from the customer for this order
SHIPPED - the products have been dispatched to the customer
COMPLETE - the customer has received the order
CANCELLED - the customer has stopped the order
REFUNDED - there has been an issue with the order and the money has been returned to the customer';
COMMENT ON COLUMN "CO"."ORDERS"."ORDER_TMS" IS 'When the order was placed';
COMMENT ON COLUMN "CO"."ORDERS"."STORE_ID" IS 'Where this order was placed';

